#!/usr/bin/env python3

import os
import subprocess
import sys


def notify(text):
    subprocess.check_call(['notify-send',
                           '-c', 'im.received',
                           '-a', 'mcabber',
                           text])


if len(sys.argv) == 5:
    event, arg1, arg2, filename = sys.argv[1:5]
elif len(sys.argv) == 4:
    event, arg1, arg2 = sys.argv[1:4]
    filename = None
else:
    print("Unexpected number of arguments: " + str(sys.argv))
    sys.exit(1)

try:

    assert event is not None
    assert arg1 is not None
    assert arg2 is not None

    if event == 'MSG' and arg1 == 'IN':
        notify('New message from {}'.format(arg2))
    elif event == 'MSG' and arg1 == 'MUC':
        notify('New message in room {}'.format(arg2))

finally:
    if filename is not None:
        try:
            os.remove(filename)
        except OSError:
            pass
